export const ListBooks = [
  {
    name: "Father Brown. Essential Tales",
    author: "Честертон Гилберт Кит",
    price: 670 ,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "Рассказы об отце Брауне английского писателя Гилберта Кита Честертона стали классикой детективного жанра. Неадаптированное издание на английском языке.",
  },
  {
    name: "Treasure Island",
    author: " Стивенсон Роберт Льюис",
    price: 543,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "Роман шотландского писателя Роберта Льюиса Стивенсона 'Остров сокровищ' полтора века остается одной из главных книг для юношества.",
  },
  {
    name: "Bodas de sangre. Trilogia Lorquiana",
    author: " Lorca Federico Carcia",
    price: 332,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "Федерико Гарсиа Лорка — великий испанский поэт и драматург, реформатор испанского театра. Пьесы «Кровавая свадьба», «Йерма» и «Дом Бернарды Альбы» — драматическая трилогия об испанской земле, «о жгучем противоборстве страстей» и о крушении надежд женщин, главных героинь всех трех произведений. Андалусия — край не только тенистых садов, виноградников, оливковых рощ, но и область бесплодных степей и скалистых пустынь. Мотив женитьбы в трагедиях увязывается с мотивами земли, плодородия и социального равенства.",
  },
  {
    name: "Los Caranchos de la Florida",
    author: "Lynch Benito",
    price: 362,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "Действие романа «Стервятники „Флориды”» аргентинского писателя Бенито Линча разворачивается в степном скотоводческом поместье. Хозяин ранчо Дон Франсиско Суарес Орофио, получивший землю от старого крестьянина-гаучо, потратил 30 лет своей жизни на развитие поместья. Любовная драма начинается с возвращения домой его сына Панчито.",
  },
  {
    name: "At the Mountains of Madness",
    author: "Лавкрафт Говард Филлипс",
    price: 292,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "Повесть американского писателя Говарда Филлипса Лавкрафта 'Хребты безумия' написана в жанре ужасов и фантастики",
  },
  {
    name: "The Couple Next Door",
    author: "Lapena Shari",
    price: 1027,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "Your neighbour told you that she didn't want your six-month-old daughter at the dinner party. Nothing personal, she just couldn't stand her crying. Your husband said it would be fine. After all, you only live next door. You'll have the baby monitor and you'll take it in turns to go back every half hour. Your daughter was sleeping when you checked on her last. But now, as you race up the stairs in your deathly quiet house, your worst fears are realized.",
  },
  {
    name: "Outliers. The Story of Success",
    author: "Gladwell Malcolm",
    price: 904,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "Why are people successful? For centuries, humankind has grappled with this question, searching for the secret to accomplishing great things. In this stunning new book, Malcolm Gladwell takes us on an invigorating intellectual journey to show us what makes an extreme overachiever.",
  },
  {
    name: "History & Mathematics",
    author: "Гринин Леонид Ефимович, Гринин Антон Леонидович",
    price: 475,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "The present Yearbook is subtitled Historical and Technological Dynamics: Factors, Cycles, and Trends. Its articles demonstrate different forms, patterns, and modes of evolutionary development of societies and their subsystems both over very long periods (in fact, the whole historical process) and over relatively short time intervals. We believe that without an in-depth analysis of the forms and mechanisms of development, it is more difficult to understand both the dynamics of the historical process and many contemporary issues rooted in history.",
  },
  {
    name: "Iranians on the Move. Migration Trends and the Role of the Diaspora. Monograph",
    author: "Afzali Mehdi, Ryazantsev Sergey Vasilyevich",
    price: 338,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "This monograph is a study of trends in emigration from Iran and the role of Iranian diasporas in developing the country. The book is based on Mehdi Afzali's dissertation research, 'The contribution of emigration to the socio-economic development of Iran,' carried out under the guidance of Professor S. V. Ryazantsev, as well as materials from other studies of Iranian migration, carried out by the authors jointly in 2017-2021.",
  },
  {
    name: "Deadly Cross",
    author: "Паттерсон Джеймс",
    price: 1027,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "A scandalous double homicide opens the psychological case files on Alex Cross... When a glamorous socialite and a high school principal are found murdered, the shocking double homicide dominates tabloid headlines. Detective Alex Cross knew both victims well, especially Kay who had been his patient once. And maybe more.",
  },
  {
    name: "Classic Tales оf Horror",
    author: "Bierce Ambrose, Ле Фаню Джозеф Шеридан, Шелли Мэри",
    price: 1342,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "Eerily vivid and yet never devoid of the beat of the human heart, Classic Tales of Horror presents the work of some of the world's most celebrated horror writers. This compilation is designed to provide both a gripping read and glimpses of life beyond the realm of the everyday. Spooks and inexplicable things that go bump in the night have long exercised creative imaginations and provided source material for our greatest story-tellers, as this memorable collection confirms.",
  },
  {
    name: " Empire of Storms",
    author: "Маас Сара Дж.",
    price: 1161,
    rating: 5,
    genre: "bilinguals",
    image: "",
    info: "Kingdoms collide in Sarah J. Maas's epic fifth installment in the New York Times bestselling Throne of Glass series. The long path to the throne has only just begun for Aelin Galathynius. Loyalties have been broken and bought, friends have been lost and gained, and those who possess magic find themselves at odds with those who don't.With her heart sworn to the warrior-prince by her side, and her fealty pledged to the people she is determined to save, Aelin will delve into the depths of her power to protect those she loves. But as monsters emerge from the horrors of the past, and dark forces become poised to claim her world, the only chance for salvation will lie in a desperate quest that may mark the end of everything Aelin holds dear.",
  }
];
